# Generated by Django 4.2 on 2023-04-28 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horaires_Roulements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('entrepriseName', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=50)),
                ('emplacement', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('signaler', models.BooleanField()),
                ('star', models.FloatField()),
                ('manyOffer', models.BooleanField()),
                ('haveHerSite', models.BooleanField()),
                ('salaire', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publi_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBack.publication')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBack.type')),
            ],
        ),
        migrations.CreateModel(
            name='Publi_HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBack.horaires_roulements')),
                ('id_publi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBack.publication')),
            ],
        ),
    ]
