# Generated by Django 4.2 on 2023-04-28 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publi_hr',
            name='id_hr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myBack.horaires_roulements'),
        ),
        migrations.AlterField(
            model_name='publi_type',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myBack.type'),
        ),
    ]
