# Generated by Django 4.2 on 2023-04-28 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBack', '0002_alter_publi_hr_id_hr_alter_publi_type_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaires_roulements',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publi_hr',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publi_hr',
            name='id_hr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBack.horaires_roulements'),
        ),
        migrations.AlterField(
            model_name='publi_type',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publi_type',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBack.type'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
