# Generated by Django 4.2 on 2023-04-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBack', '0003_alter_horaires_roulements_id_alter_publi_hr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
